# Generated by Django 5.1 on 2024-10-03 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabinnum',
            options={'verbose_name': 'booked cabin', 'verbose_name_plural': 'booked cabins'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'cabin Visitor'},
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='with_kid',
            new_name='with_family',
        ),
        migrations.AlterField(
            model_name='cabinnum',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.visitor'),
        ),
    ]
